Task 1: Creating and Manipulating Arrays.

In [2]:
import numpy as np

# Create a 1-dimensional NumPy array with 10 elements of your choice
array = np.array([5, 11, 8, 3, 5, 15, 20, 1, 9, 18])

# Print the array
print(array)


[ 5 11  8  3  5 15 20  1  9 18]


In [3]:
import numpy as np

# Create a 2-dimensional NumPy array with shape (3, 4) containing random integers between 1 and 20
array = np.random.randint(1, 21, size=(3, 4))

# Print the array
print(array)


[[ 5  8 20 19]
 [12 16  4 14]
 [ 8 15  3 17]]


In [5]:
import numpy as np

# Create the original 2D array with shape (3, 4)
array = np.random.randint(1, 21, size=(3, 4))
print("Original 2D array (3x4):")
print(array)

# Reshape the array into a 4x3 array
reshaped_array_4x3 = array.reshape(4, 3)
print("\nReshaped 2D array (4x3):")
print(reshaped_array_4x3)

# Reshape the array into a 1D array
reshaped_array_1D = reshaped_array_4x3.reshape(-1)
print("\nReshaped 1D array:")
print(reshaped_array_1D)

# Slice the first 5 elements from the 1D array
sliced_array = reshaped_array_1D[:5]
print("\nFirst 5 elements of the 1D array:")
print(sliced_array)


Original 2D array (3x4):
[[ 5  6 18  1]
 [15  3 13 17]
 [ 6 15  2 18]]

Reshaped 2D array (4x3):
[[ 5  6 18]
 [ 1 15  3]
 [13 17  6]
 [15  2 18]]

Reshaped 1D array:
[ 5  6 18  1 15  3 13 17  6 15  2 18]

First 5 elements of the 1D array:
[ 5  6 18  1 15]


In [6]:
import numpy as np

# Create an array of zeros with shape (2, 3)
zeros_array = np.zeros((2, 3))
print("Array of zeros (2x3):")
print(zeros_array)

# Create an array of ones with shape (3, 2)
ones_array = np.ones((3, 2))
print("\nArray of ones (3x2):")
print(ones_array)


Array of zeros (2x3):
[[0. 0. 0.]
 [0. 0. 0.]]

Array of ones (3x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]]


Task 2: Array Operations.

In [7]:
import numpy as np

# Create two arrays of your choice
array1 = np.array([10, 20, 30, 40])
array2 = np.array([1, 2, 3, 4])

# Perform element-wise addition
addition = array1 + array2
print("Element-wise addition:")
print(addition)

# Perform element-wise subtraction
subtraction = array1 - array2
print("\nElement-wise subtraction:")
print(subtraction)

# Perform element-wise multiplication
multiplication = array1 * array2
print("\nElement-wise multiplication:")
print(multiplication)

# Perform element-wise division
division = array1 / array2
print("\nElement-wise division:")
print(division)


Element-wise addition:
[11 22 33 44]

Element-wise subtraction:
[ 9 18 27 36]

Element-wise multiplication:
[ 10  40  90 160]

Element-wise division:
[10. 10. 10. 10.]


In [8]:
import numpy as np

# Create two 2D arrays with compatible shapes
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8],
                   [9, 10],
                   [11, 12]])

# Compute the dot product of the two arrays
dot_product = np.dot(array1, array2)

# Print the result
print("Dot product of the two arrays:")
print(dot_product)


Dot product of the two arrays:
[[ 58  64]
 [139 154]]


In [9]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.identity(3)

# Print the identity matrix
print("3x3 Identity matrix:")
print(identity_matrix)


3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
import numpy as np

# Create a 1D array
array = np.array([10, 20, 30, 40, 50])

# Calculate the sum
sum_array = np.sum(array)
print("Sum of the array:", sum_array)

# Calculate the mean
mean_array = np.mean(array)
print("Mean of the array:", mean_array)

# Calculate the standard deviation
std_dev_array = np.std(array)
print("Standard deviation of the array:", std_dev_array)

# Calculate the variance
variance_array = np.var(array)
print("Variance of the array:", variance_array)


Sum of the array: 150
Mean of the array: 30.0
Standard deviation of the array: 14.142135623730951
Variance of the array: 200.0


Task 3: Boolean Indexing and Filtering.

In [11]:
import numpy as np

# Create a 1D array with 15 random integers between 0 and 50
array = np.random.randint(0, 51, size=15)
print("Original array:")
print(array)

# Use Boolean indexing to filter out all elements greater than 25
filtered_array = array[array <= 25]
print("\nFiltered array (elements <= 25):")
print(filtered_array)

# Replace all values in the array that are less than 10 with 10
array[array < 10] = 10
print("\nArray with values < 10 replaced by 10:")
print(array)


Original array:
[15 30 16 48 43  8  1  4 20  2 36 25 11 21  9]

Filtered array (elements <= 25):
[15 16  8  1  4 20  2 25 11 21  9]

Array with values < 10 replaced by 10:
[15 30 16 48 43 10 10 10 20 10 36 25 11 21 10]


Task 4: Advanced Operations.

In [14]:
import numpy as np

# Generate a 5x5 matrix with random integers between 0 and 100
matrix = np.random.randint(0, 101, size=(5, 5))
print("5x5 Matrix:")
print(matrix)

# Find the minimum and maximum values in the matrix
min_value = np.min(matrix)
max_value = np.max(matrix)
print("\nMinimum value in the matrix:", min_value)
print("Maximum value in the matrix:", max_value)

# Calculate the row-wise sums of the matrix
row_sums = np.sum(matrix, axis=1)
print("\nRow-wise sums:")
print(row_sums)

# Calculate the column-wise sums of the matrix
column_sums = np.sum(matrix, axis=0)
print("\nColumn-wise sums:")
print(column_sums)


5x5 Matrix:
[[ 7 31 45 66  9]
 [32 55 30 57 99]
 [21 37 53 56 66]
 [81 50 96 95 59]
 [48 36 89 10 95]]

Minimum value in the matrix: 7
Maximum value in the matrix: 99

Row-wise sums:
[158 273 233 381 278]

Column-wise sums:
[189 209 313 284 328]


In [15]:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

# Stack the arrays vertically
vertical_stack = np.vstack((array1, array2))
print("\nVertical stack of Array 1 and Array 2:")
print(vertical_stack)

# Stack the arrays horizontally
horizontal_stack = np.hstack((array1, array2))
print("\nHorizontal stack of Array 1 and Array 2:")
print(horizontal_stack)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Vertical stack of Array 1 and Array 2:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Horizontal stack of Array 1 and Array 2:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
